/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JFizz */

#ifndef _Included_JFizz
#define _Included_JFizz
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JFizz
 * Method:    fizzy
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JFizz_fizzy
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
